modLoader = "javafml"
loaderVersion = "[31,)"
issueTrackerURL = "https://github.com/Kamefrede/AdvanceMeNot/issues"

license = "MIT"
[[mods]]
modId = "advancemenot"
version = "${file.jarVersion}"
displayName = "AdvanceMeNot!"
credits = "Commissioned by dani, delivered with love by Kamefrede"
authors = "Kamefrede, dani"
description = '''
Block players from getting advancements in certain dimensions with one simple command!(Also blocks recipe unlocks)
'''
[[dependencies.advancemenot]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.advancemenot]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"
